// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type HealthRequest struct {
}

type HealthResponse struct {
	Status string `json:"status"` // 服务状态: ok-正常, error-异常
}

type PingUserServiceRequest struct {
}

type PingUserServiceResponse struct {
	ID            int    `json:"id"`              // 用户唯一标识
	Name          string `json:"name"`            // 用户姓名
	SAPEmployeeID int    `json:"sap_employee_id"` // SAP 员工编号
}
