// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	ping "go-zero-template/internal/handler/ping"
	system "go-zero-template/internal/handler/system"
	"go-zero-template/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 调用用户服务
					Method:  http.MethodGet,
					Path:    "/user",
					Handler: ping.PingUserServiceHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/cron/ping"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 健康检查
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: system.HealthHandler(serverCtx),
			},
		},
	)
}
